# Generated by Django 6.0.1 on 2026-02-17 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_engineerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='category',
            field=models.CharField(choices=[('NETWORK', 'Network Operations'), ('CLOUD', 'Cloud Infrastructure'), ('SERVER', 'Server Administration'), ('DATABASE', 'Database Administration'), ('DEVOPS', 'DevOps'), ('CYBER', 'Cybersecurity'), ('RISK', 'Risk & Compliance'), ('APP', 'Application Support'), ('AI', 'AI / ML Operations'), ('DATA', 'Data Engineering'), ('SRE', 'Site Reliability Engineering'), ('INCIDENT', 'Incident Response')], default='Cybersecurity', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.department'),
        ),
    ]
