# Generated by Django 6.0.1 on 2026-02-18 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_ticket_category_ticket_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='engineerprofile',
            name='department',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='category',
            field=models.CharField(choices=[('NETWORK', 'Network Operations'), ('CLOUD', 'Cloud Infrastructure'), ('SERVER', 'Server Administration'), ('DATABASE', 'Database Administration'), ('DEVOPS', 'DevOps'), ('CYBER', 'Cybersecurity'), ('RISK', 'Risk & Compliance'), ('APP', 'Application Support'), ('AI', 'AI/ML Operations'), ('DATA', 'Data Engineering'), ('SRE', 'SRE'), ('INCIDENT', 'Incident Response')], max_length=50),
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.department')),
            ],
        ),
        migrations.AddField(
            model_name='engineerprofile',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.team'),
        ),
    ]
