# Generated by Django 6.0.1 on 2026-02-18 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_engineerprofile_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='engineerprofile',
            name='is_team_lead',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='engineerprofile',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.team'),
        ),
    ]
