# Generated by Django 6.0.1 on 2026-02-18 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_engineerprofile_is_team_lead_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engineerprofile',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.team'),
        ),
    ]
