# Generated by Django 6.0.1 on 2026-02-18 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_engineerprofile_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='sla_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
