# Generated by Django 6.0.1 on 2026-02-19 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_ticketaudit'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='pause_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='sla_paused',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ticket',
            name='total_pause_duration',
            field=models.FloatField(default=0),
        ),
    ]
