# Generated by Django 6.0.1 on 2026-02-20 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved'), ('REOPENED', 'Reopened'), ('BREACHED', 'Breached')], default='NEW', max_length=20),
        ),
    ]
